version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - Dadavan
  - nikolay-udovik
  - Rachunc
  - shamil
  - Shareed2k

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - Dadavan
  - nikolay-udovik
  - Rachunc
  - shamil
  - Shareed2k

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - Dadavan
  - nikolay-udovik
  - Rachunc
  - shamil
  - Shareed2k
